# Generated by Django 2.0.7 on 2018-07-27 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
                ('booktitle', models.CharField(default='', max_length=200, verbose_name='Paper Title')),
                ('bookname', models.CharField(default='', max_length=200, verbose_name='Book Title')),
                ('bpublishedon', models.DateField(default=datetime.date.today, verbose_name='Publication on:')),
                ('pubfromconf', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, verbose_name='Through conf.')),
                ('bsjr', models.FloatField(blank=True, null=True, verbose_name='SJR')),
                ('bsnip', models.FloatField(blank=True, null=True, verbose_name='SNIP')),
                ('bisbn', models.FloatField(blank=True, null=True, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
                ('ctitle', models.CharField(default='', max_length=200, verbose_name='Paper Title')),
                ('cname', models.CharField(default='', max_length=200, verbose_name='Conference Name')),
                ('presentedby', models.CharField(max_length=50, verbose_name='Presented By')),
                ('conferencecategory', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='International', max_length=50, verbose_name='Conference Category')),
                ('cdatefrom', models.DateField(verbose_name='Conference Date From: ')),
                ('cdateto', models.DateField(verbose_name='Conference Date To: ')),
                ('venue', models.CharField(max_length=100, verbose_name='Venue')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('csjr', models.FloatField(blank=True, null=True, verbose_name='SJR')),
                ('csnip', models.FloatField(blank=True, null=True, verbose_name='SNIP')),
                ('cisbn', models.FloatField(blank=True, null=True, verbose_name='ISBN')),
                ('pubtojournalorbook', models.CharField(choices=[('No', 'No'), ('Journal', 'Journal'), ('Book Series', 'Book Series')], default='No', max_length=50, verbose_name='To be Published as Journal/ Book')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=50, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('facultyname', models.CharField(max_length=100, verbose_name='Faculty Name')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchapp.Department', verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
                ('jtitle', models.CharField(default='', max_length=200, verbose_name='Paper Title')),
                ('jname', models.CharField(default='', max_length=200, verbose_name='Journal Name')),
                ('jstatus', models.CharField(choices=[('Accepted', 'Accepted'), ('Submitted', 'Submitted'), ('Published', 'Published'), ('Under Review', 'Under Review')], default='Published', max_length=15, verbose_name='Publication Status')),
                ('jpublishedon', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('jvolno', models.IntegerField(blank=True, null=True, verbose_name='Volume')),
                ('jissueno', models.IntegerField(blank=True, null=True, verbose_name='Issue No')),
                ('jpageno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Page No')),
                ('jtr', models.FloatField(blank=True, null=True, verbose_name='SCI-IF')),
                ('jsjr', models.FloatField(blank=True, null=True, verbose_name='SJR')),
                ('jsnip', models.FloatField(blank=True, null=True, verbose_name='SNIP')),
                ('jissn', models.IntegerField(blank=True, null=True, verbose_name='ISSN NO')),
                ('pubfromconf', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Through conf.')),
                ('paynopay', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Paid Journal')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country, published from')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
                ('facultyauthor', models.ManyToManyField(max_length=100, to='researchapp.Faculty', verbose_name='Faculty Author')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=200, verbose_name='Project Title')),
                ('fundingagency', models.CharField(max_length=200, verbose_name='Funding Agency')),
                ('projectcategory', models.CharField(choices=[('External', 'External'), ('Internal Faculty', 'Internal Faculty'), ('Internal Student', 'Internal Student')], default='External', max_length=50, verbose_name='Project Category')),
                ('projectstatus', models.CharField(choices=[('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Results Pending', 'Results Pending'), ('Rejected', 'Rejected')], default='Ongoing', max_length=50, verbose_name='Project Status')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('sanctioneddate', models.DateField(verbose_name='Sanctioned Date')),
                ('sanctionedamount', models.FloatField(blank=True, null=True, verbose_name='Sanctioned Amount')),
                ('fundreleasedon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fund Released On')),
                ('amountreceived', models.CharField(blank=True, max_length=200, null=True, verbose_name='Amount Received')),
                ('completiondate', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('outcome', models.TextField(blank=True, max_length=500, verbose_name='Outcome')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('facultycopi', models.ManyToManyField(blank=True, related_name='projectcopis', to='researchapp.Faculty', verbose_name='Co-Principal Investigator')),
                ('facultypi', models.ManyToManyField(blank=True, related_name='projectpis', to='researchapp.Faculty', verbose_name='Principal Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchScholar',
            fields=[
                ('rsname', models.CharField(max_length=100, verbose_name='Student Name')),
                ('rsregno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Registration Number')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchapp.Department', verbose_name='Department Name')),
                ('rssupervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchapp.Faculty', verbose_name="Supervisor's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sregno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Registration Number')),
                ('sname', models.CharField(max_length=100, verbose_name='Student Name')),
                ('sbranch', models.CharField(max_length=50, verbose_name='Branch')),
                ('sbatch', models.CharField(max_length=20, verbose_name='Batch')),
                ('studentcategory', models.CharField(choices=[('UG Student', 'UG Student'), ('PG Student', 'PG Student')], default='UG Student', max_length=20, verbose_name='Student Category')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchapp.Department', verbose_name='Department Name')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rs',
            field=models.ManyToManyField(blank=True, to='researchapp.ResearchScholar', verbose_name='Research Scholar'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, to='researchapp.Student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='rsauthor',
            field=models.ManyToManyField(blank=True, max_length=100, to='researchapp.ResearchScholar', verbose_name='Research Scholar Author'),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='studentauthor',
            field=models.ManyToManyField(blank=True, max_length=100, to='researchapp.Student', verbose_name='Student Author'),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='facultyauthor',
            field=models.ManyToManyField(max_length=100, to='researchapp.Faculty', verbose_name='Faculty Author'),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='rsauthor',
            field=models.ManyToManyField(blank=True, max_length=100, to='researchapp.ResearchScholar', verbose_name='Research Scholar Author'),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='studentauthor',
            field=models.ManyToManyField(blank=True, max_length=100, to='researchapp.Student', verbose_name='Student Author'),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='facultyauthor',
            field=models.ManyToManyField(to='researchapp.Faculty', verbose_name='Faculty Author'),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='rsauthor',
            field=models.ManyToManyField(blank=True, to='researchapp.ResearchScholar', verbose_name='Research Scholar Author'),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='studentauthor',
            field=models.ManyToManyField(blank=True, to='researchapp.Student', verbose_name='Student Author'),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
